//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "organizations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub logo_url: String,
    #[sea_orm(column_type = "Text")]
    pub billing_email_address: String,
    pub billing_email_verified: bool,
    #[sea_orm(column_type = "Text")]
    pub origin: String,
    pub start_date: Date,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub created_by: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::admins::Entity",
        from = "Column::CreatedBy",
        to = "super::admins::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Admins,
    #[sea_orm(has_many = "super::organization_invite::Entity")]
    OrganizationInvite,
    #[sea_orm(has_many = "super::roles::Entity")]
    Roles,
}

impl Related<super::admins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Admins.def()
    }
}

impl Related<super::organization_invite::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationInvite.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
