//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::admins::Entity as Admins;
pub use super::organization_invite::Entity as OrganizationInvite;
pub use super::organizations::Entity as Organizations;
pub use super::roles::Entity as Roles;
pub use super::users::Entity as Users;
