//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "account_source_enum"
)]
pub enum AccountSourceEnum {
    #[sea_orm(string_value = "google")]
    Google,
    #[sea_orm(string_value = "credentials")]
    Credentials,
    #[sea_orm(string_value = "github")]
    Github,
}
