[workspace]
members = [
    "server",
    "redis",
    "database",
    "worker",
    "tests",
    "sfu",
    "common",
    "judge",
    "redis",
]
default-members = ["server", "database", "worker", "common", "redis"]
resolver = "3"


[workspace.package]
homepage = "https://manthansharma.in/"

[workspace.metadata]
